version: '3.9'

services:
  scholar_hive_db:
    image: postgres:latest
    container_name: scholar_hive_db
    environment:
      POSTGRES_DB: scholar_hive_db
      POSTGRES_USER: scholar_hive_user
      POSTGRES_PASSWORD: scholar_hive_password
    ports:
      - "20505:5432"
    volumes:
      - scholar_hive_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scholar_hive_user -d scholar_hive_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - scholar_hive_network

  scholar_hive_app:
    image: kyantech/scholar-hive:beta-0.0.1
    container_name: scholar_hive_app
    environment:
      - DATABASE_URL=postgresql://scholar_hive_user:scholar_hive_password@scholar_hive_db:5432/scholar_hive_db
      - AUTH_SECRET=EZ0Q4x1tICQ1fbw7LUtKQUkpvjPWLTTUd5jxcL5rI7I=
      - NEXTAUTH_URL=http://localhost:1996
      - AUTH_TRUST_HOST=true
    ports:
      - "1996:3000"
    depends_on:
      scholar_hive_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - scholar_hive_network

volumes:
  scholar_hive_data:
    name: scholar_hive_data

networks:
  scholar_hive_network:
    name: scholar_hive_network
    driver: bridge
