version: '3.9'

services:
  # DATABASE
  scholar_hive_db:
    image: postgres:latest
    container_name: scholar_hive_db
    environment:
      POSTGRES_DB: scholar_hive_db
      POSTGRES_USER: scholar_hive_user
      POSTGRES_PASSWORD: scholar_hive_password
    ports:
      - "20505:5432"
    volumes:
      - scholar_hive_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scholar_hive_user -d scholar_hive_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - scholar_hive_network

volumes:
  scholar_hive_data:
    name: scholar_hive_data

networks:
  scholar_hive_network:
    name: scholar_hive_network
    driver: bridge
